### ISSUE TITLE
Ability to keep a link to a specific job linting

### ISSUE THREAD

**Issue by gortok** [rowanmanning/joblint#82]
Right now we can't link to a job linting; the best we can do is paste the text and take a screenshot. 

I'm thinking more of a plunker for these joblints; where each paste creates a temporary (or permanent) shortlink that can be linked to.

I'm willing to do the work for this; but I want to be sure to get consensus for it first.

**Comment by rowanmanning** [comment]
Hi George, I'd love to get this working but we have two small issues to consider:

Firstly, the Joblint site is static and hosted on GitHub pages. So the link would need to contain the full job post in a query param or something like that. We could make the links more manageable by using a URL shortener.

Secondly, posts are saved to local storage. We'd maybe want to disable this functionality if the user has followed a link to a saved lint otherwise it could override something they've been working on. I think the nicest way to expose this would be through some kind of auto-save toggle in the UI which defaults to "off" if the query parameter is present.

**Comment by gortok** [comment]
@rowanmanning Depending on how many requests per minute we're getting, we could possibly get away with a backend storage service like Parse.com.  But yea, then URLs would be unique identifiers to this data (which seems normal).
